### ISSUE TITLE
OpenWebText non-toxic corpus 

### ISSUE THREAD

**Issue by gulleh** [alisawuffles/DExperts#1]
Hi,

Is it possible to provide the non-toxic set of OpenWebText required for training DAPT or even better providing the finetuned model? Unfortunately, I do not know the exact steps required to make such dataset.

Thanks.

**Comment by alisawuffles** [comment]
Hi there, thanks for the question! I have updated the README to include instructions on downloading both the non-toxic set of OWT, as well as the trained nontoxic DAPT model. If you have any questions or trouble, please do let me know!

**Comment by gulleh** [comment]
Thanks a lot for sharing the dataset and the model. I have another question regarding the notebook files. It seems that the numbers (for toxicity) are not the same as the paper (Table 1). For example, perplexity in Table 1 for DExperts (anti-only)  is 8.03 while in the notebook is 52.022. Is it the problem with the notebook?

**Comment by alisawuffles** [comment]
Are you sure you are looking at the camera-ready version of our paper? https://arxiv.org/pdf/2105.03023.pdf

The reason for the different perplexity numbers between the ACL submission version and ACL camera-ready is because originally, we fed the entire text file of generations into GPT-2 XL for evaluation; by default, it would use a large block size such that it was also conditioning on _previous_ generations for the same prompt. This results in much lower perplexity overall. For the camera-ready, we fixed this so that we were evaluating perplexity one sentence at a time, and then averaging those perplexity scores.

**Comment by gulleh** [comment]
No, I did not know about the camera-ready version. Thanks a lot for providing the paper and detailed explanation.
